# Generated by Django 3.2.19 on 2023-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0002_auto_20230622_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='bespoke_order_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
