# Generated by Django 3.2.19 on 2023-06-23 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('bespoke', '0003_bespokeorder_bespoke_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bespoke_orders', to='profiles.userprofile'),
        ),
    ]
